name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8" # oder die Version, die du benötigst

      - name: Install dependencies
        run: |
          pip install unittest

      - name: Run tests
        run: |
          python test.py  # Oder den Pfad zu deiner Testdatei
